export const GET_CITY = "GET_CITY";
export const GET_CITY_FAIL = "GET_CITY_FAIL";
export const CHANGE_RESULT = "CHANGE_RESULT";
export const CURRENT_CITY_INDEX = "CURRENT_CITY_INDEX";
export const GET_CURRENT_LOCATION = "GET_CURRENT_LOCATION";
export const GET_CURRENT_LOCATION_FAIL = "GET_CURRENT_LOCATION_FAIL";
