export const GET_CITIES = "GET_CITIES";
export const GET_CITIES_FAIL = "GET_CITIES_FAIL";
export const GET_CITIES_SUCCESS = "GET_CITIES_SUCCESS";
export const CHANGE_RESULT = "CHANGE_RESULT";
export const CURRENT_CITY_INDEX = "CURRENT_CITY_INDEX";
export const GET_CURRENT_LOCATION = "GET_CURRENT_LOCATION";
export const GET_CURRENT_LOCATION_FAIL = "GET_CURRENT_LOCATION_FAIL";
export const CHANGE_KEYWORD_SEARCH = "CHANGE_KEYWORD_SEARCH";
